Update

diff --git a/scripts/build_image b/scripts/build_image
--- a/scripts/build_image
+++ b/scripts/build_image
@@ -1,12 +1,12 @@
 #!/bin/bash
-set -eo pipefail  # Exit immediately if a command exits with a non-zero status, and ensure errors in pipelines are caught
+# set -eo pipefail  # Exit immediately if a command exits with a non-zero status, and ensure errors in pipelines are caught
 
 # Function to print the usage guide for the script
 print_usage() {
     cat <<EOF
 Usage: bash build_image.sh [OPTIONS]
 
-This script builds an apptainer image based on a definition file located in the build directory.
+This script builds an project's Apptainer image based on a definition file located in the build directory.
 
 Options:
   -h, --help    Show this help message and exit.
@@ -60,10 +60,10 @@ build_image() {
         export APPTAINER_TMPDIR="${HOME}/.apptainer_tmp"
         export APPTAINER_CACHEDIR="${HOME}/.apptainer_cache"
         # Build the image with Nvidia GPU support, logging output to the log file
-        sudo -E apptainer build --nv "${IMAGE_FILE}" "${DEFINITION_FILE}" 2>&1 | tee "${BUILD_LOG_FILE}"
+        sudo -E apptainer build --nv --build-arg SSH_DIR="${HOME}/.ssh" "${IMAGE_FILE}" "${DEFINITION_FILE}" 2>&1 | tee "${BUILD_LOG_FILE}"
     else
         # Build the image with Nvidia GPU support, logging output to the log file
-        sudo apptainer build --nv "${IMAGE_FILE}" "${DEFINITION_FILE}" 2>&1 | tee "${BUILD_LOG_FILE}"
+        sudo apptainer build --nv --build-arg SSH_DIR="${HOME}/.ssh" "${IMAGE_FILE}" "${DEFINITION_FILE}" 2>&1 | tee "${BUILD_LOG_FILE}"
     fi
 }
 
diff --git a/scripts/start_container b/scripts/start_container
--- a/scripts/start_container
+++ b/scripts/start_container
@@ -1,17 +1,17 @@
 #!/bin/bash
-set -eo pipefail  # Exit immediately if a command fails and ensure errors in pipelines are caught
+# set -eo pipefail  # Exit immediately if a command fails and ensure errors in pipelines are caught
 
 # Function to print the usage information for this script
 print_usage() {
     cat <<EOF
-Usage: bash start_container.sh [OPTIONS]
+Usage: bash start_container [OPTIONS]
 
-This script starts a RoboTour Apptainer container. It performs the following steps:
+This script starts a project's Apptainer container. It performs the following steps:
 
-  1. Validates the environment and dependencies.
-  2. Checks if the necessary Apptainer image is available.
-  3. Sets up the environment variables required for the container.
-  4. Launches the Apptainer container with appropriate configurations.
+    1. Checks if Apptainer is installed and installs it if not.
+    2. Checks if the specified image file exists and downloads it if not.
+    3. Warns the user if NVIDIA GPU support is not enabled.
+    4. Starts the Apptainer container with the specified image file.
 
 Options:
   -h, --help    Show this help message and exit.
@@ -89,8 +89,7 @@ main() {
 
         # If the user agrees to download the image, ask for the username and download it
         if [[ $REPLY =~ ^[Yy]$ ]]; then
-            read_input "Enter the username for the remote server ${PINK}${REMOTE_SERVER}${RESET}: "
-            bash "${SCRIPTS_DIR}/transfer_image.sh" download -u "$REPLY"
+            bash "${SCRIPTS_DIR}/transfer_image" download
         else
             exit 1  # Exit if the user chooses not to download the image
         fi
