Update

diff --git a/scripts/start_container b/scripts/start_container
--- a/scripts/start_container
+++ b/scripts/start_container
@@ -1,5 +1,5 @@
 #!/bin/bash
-# set -eo pipefail  # Exit immediately if a command fails and ensure errors in pipelines are caught
+set -eo pipefail  # Exit immediately if a command fails and ensure errors in pipelines are caught
 
 # Function to print the usage information for this script
 print_usage() {
@@ -16,6 +16,7 @@ This script starts a project's Apptainer container. It performs the following st
 Options:
   -h, --help    Show this help message and exit.
   --nv          Enable NVIDIA GPU support in the container.
+  --overlay     Enable overlay mode for the container.
 EOF
 }
 
@@ -31,8 +32,10 @@ source "$(realpath "$(dirname "${BASH_SOURCE[0]}")")/utils/functions.sh"
 
 # Main function to handle the execution of the script
 main() {
+    overlay=""             # Default is no overlay mode
     nvidia_gpu=""          # Default is no NVIDIA GPU support
     download_image=false   # Flag for image download, currently not used
+    is_overlay_enabled=false  # Flag to check if overlay mode is enabled
 
     # Parse command-line arguments
     while [[ $# -gt 0 ]]; do
@@ -44,6 +47,10 @@ main() {
             ;;
             --nv)
             nvidia_gpu="--nv"  # Enable NVIDIA GPU support
+            shift # Move to the next argument
+            ;;
+            --overlay)
+            is_overlay_enabled=true  # Enable overlay mode
             shift # Move to the next argument
             ;;
             *)
@@ -66,7 +73,7 @@ main() {
 
     # Check if Apptainer is installed, and install it if not
     if ! is_apptainer_installed; then
-        error_log "Apptainer is not installed. Please install it first."
+        warn_log "Apptainer is not installed. Please install it first."
         read_input "Do you want to install ${CYAN}Apptainer${RESET} now? (y/N) " response
 
         # If the user agrees to install Apptainer, run the installation script
@@ -84,7 +91,7 @@ main() {
 
     # Check if the specified image file exists
     if [ ! -f "$IMAGE_FILE" ]; then
-        error_log "Image file ${PINK}${IMAGE_FILE}${RESET} does not exist."
+        warn_log "Image file ${PINK}${IMAGE_FILE}${RESET} does not exist."
         read_input "Do you want to download the image? [y/N] "
 
         # If the user agrees to download the image, ask for the username and download it
@@ -101,12 +108,23 @@ main() {
         \ran NVIDIA GPU, you can enable it by using the ${YELLOW}--nv${RESET} option."
     fi
 
+    # Choose an overlay
+    if [ "$is_overlay_enabled" = true ]; then
+        select_overlay
+    fi
+    echo "Overlay: ${OVERLAY_ARG}"
+
 
     export APPTAINERENV_WORKSPACE_DIR="${WORKSPACE_DIR}"
 
     # Log the start of the container and execute the container with the appropriate settings
-    info_log "Starting Apptainer container from image ${PINK}$(basename "${IMAGE_FILE}")${RESET}."
-    apptainer exec $nvidia_gpu -B "${MOUNT_PATHS[$HARDWARE_TYPE]}" -e $IMAGE_FILE "${SCRIPTS_DIR}/utils/init_workspace.sh"
+    if [ "$is_overlay_enabled" = true ]; then
+        info_log "Starting Apptainer container from image ${PINK}$(basename "${IMAGE_FILE}")${RESET} with overlay image ${PINK}$(basename "${OVERLAY_IMAGE_FILE}")${RESET}."
+    else
+        info_log "Starting Apptainer container from image ${PINK}$(basename "${IMAGE_FILE}")${RESET}."
+    fi
+    
+    apptainer exec $nvidia_gpu $OVERLAY_ARG -B "${MOUNT_PATHS[$HARDWARE_TYPE]}" -e $IMAGE_FILE "${SCRIPTS_DIR}/utils/init_workspace.sh"
 }
 
 # ============= END: Main =============
